Results generation
MrLongbottom/P9-Kode pull request #28
Opened 2020-12-02 09:25 UTC by slayeren

2020-12-03 14:38 UTC, Starrock45 requested changes

2020-12-03 14:38 UTC, Starrock45 commented on query_evaluation.py
> +def mean_average_precision():
parametrer og docstring for læsbarhed

2020-12-03 14:38 UTC, Starrock45 commented on query_evaluation.py
> +    for i in range(8):
```suggestion
    for i in range(8):  # 8 because there are 8 sets of queries of different lengths
```

2020-12-03 14:38 UTC, Starrock45 commented on query_evaluation.py
> +                gtp_ranks = [ranks[query_n].index(gtp_id) for gtp_id in gtp_ids]
Hvad står `gtp` for?

2020-12-08 08:14 UTC, MrLongbottom approved these changes

2020-12-08 10:24 UTC, Starrock45 requested changes

2020-12-08 10:24 UTC, Starrock45 commented on PageRankVector.ipynb
> +{
Er det meningen at denne fil kommer med i PR'en?

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +def hit_point():
Docstring/parametre

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +    for i in range(4):
Kommentar til hvorfor range 4

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +    :param matrices: 4 ndarrays of document queries + 4 4 ndarrays of document
```suggestion
    :param matrices: 4 ndarrays of document queries + 4 ndarrays of documents
```

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +def map_function(ranks, query_n, answer):
Docstring der siger at det er mean average precision. Troede næsten at det var en mapping funktion.

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +    gtp_in_N = [x for x in ranks[query_n][:X] if x in gtp_ids]
Ved stadig ikke hvad gtp står for, da det aldrig beskrives. Kommentar eller lignende.

2020-12-08 10:24 UTC, Starrock45 commented on query_evaluation.py
> +    gtp_ranks.sort()
Samme her med gtp

2021-01-14 14:24 UTC, Starrock45 approved these changes

2021-01-14 14:36 UTC, merged