Feature/jenson shannon
MrLongbottom/P9-Kode pull request #4
Opened 2020-10-19 08:21 UTC by MrLongbottom

2020-10-20 07:06 UTC, MrLongbottom commented on matrix_construction.py
> +    max = 500
hvad er dette max? burde det ikke som standard være antal dokumenter?

2020-10-22 11:03 UTC, Starrock45 requested changes
Kommentarer til mulig navneændring, til forhåbentlig at forbedre læsbarheden.

2020-10-22 11:03 UTC, Starrock45 commented on matrix_construction.py
> +def inner_matrix_loop(td_matrix, i):
Docstrings for de to funktioner ville være godt, med en beskrivelse der siger at de bruges til JS distance udregning.

2020-10-22 11:03 UTC, Starrock45 commented on matrix_construction.py
> +def matrix_construction(td_matrix, poolsize=8):
Måske et mere beskrivende navn, hvis den kun bruges til JS Distance/generel distance udregning.

2020-10-22 11:03 UTC, Starrock45 commented on matrix_construction.py
> +def inner_matrix_loop(td_matrix, i):
Samme her med et muligvis mere beskrivende navn, som gør det åbenlyst at JS distance udregnes her.

2020-10-27 14:12 UTC, slayeren approved these changes
Hvis dennis's kommentarer bliver fixet :D så er jeg også glad

2020-10-27 14:27 UTC, Starrock45 approved these changes

2020-10-27 14:37 UTC, merged